version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  test-all:
    jobs:
      - test_regression_model

jobs:
  test_regression_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            virtualenv venv
            . venv/bin/activate
            python --version
            pip install --upgrade pip
            pip install -r packages/regression_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            pytest -v packages/regression_model/tests

