version: 2
jobs:
  test_regression_model:
    working_directory: ~/ML-with-CICD
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Running tests
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r packages/regression_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            pytest packages/regression_model/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_regression_model
